version: "3"
services:
  birds-web:
    build: ./client
    volumes:
      - ./client/:/app
    ports:
      - "3000:3000"
    links:
      - birds-server
  birds-server:
    build: ./server
    volumes:
      - ./server/:/app
    ports:
      - "3001:3001"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes_from:
      - mongodata
  mongodata:
    image: tianon/true
    volumes:
      - /data/db